### ISSUE TITLE
Hello! About Dataset...

### ISSUE THREAD

**Issue by by5747** [kuihua/MSPFN#2]
The original Rain1400 dataset consist of 12600 training samples and 1400 test samples.
Referring to table 1 in your paper, it appears that 1,400 images were taken out of the training samples and added to the test samples.
What is the criteria for choosing 1400 images?

**Comment by kuihua** [comment]
Thanks for your attention! For more convincing, we randomly selected 1400 samples from the training samples for evaluation to cover more test scenarios.

**Comment by adityac8** [comment]
Hi @kuihua 
Could you provide a list of images names taken from the public datasets. In that way people already having all these datasets can convert to your splits.
<img width="716" alt="image" src="https://user-images.githubusercontent.com/19192257/87204351-a2b93e00-c315-11ea-8fdf-e3eccd0cbe29.png">

I downloaded the `train.npy` from Baidu Cloud files but the images are resized of `96X96` size. However, I plan to use a different patch size for training my model.

Thanks

**Comment by kuihua** [comment]
Rain 14000: We sample the first 800 images from Rain1000 provided by Fu [7] to generate 800x14 rainy images with 14 streak orientations and magnitudes.
Rain 800: The first 700 images are used for training, and the following for evaluation.
In addition, you can directly download the raw image via the link in the readme (Download training dataset ((raw images)Baidu Cloud).

**Comment by adityac8** [comment]
Hi,
Could you please provide password for Raw images [link](https://pan.baidu.com/s/1pUauDe5Yr9hyK7dw_zU43Q).

Thanks

**Comment by kuihua** [comment]
I am sorry. You can download the raw datasets through the following link:
link：https://pan.baidu.com/s/1usedYAf3gYOgAJJUDlrwWg 
Password：4qnh
