### ISSUE TITLE
How can I download the pretrained models for testing my datasheet

### ISSUE THREAD

**Issue by 617778859** [kuihua/MSPFN#5]
Hi, I want to ask some questions.
Firstly, I just want to test my datasheet, and how can I download the pretrained models
Secondly, Is the Tensorflow version is 1.12 
Thanks a lot

**Comment by kuihua** [comment]
Thanks for your attention!
A1: You can download the pre-trained model from the following link:
https://pan.baidu.com/s/1gq16HTvJCHEXXc0V3t7lqw
提取码：zs3v
A2: yes, the Tensorflow version is 1.12.0 with cuda9.0

**Comment by 617778859** [comment]
> Thanks for your attention!
> A1: You can download the pre-trained model from the following link:
> https://pan.baidu.com/s/1gq16HTvJCHEXXc0V3t7lqw
> 提取码：zs3v
> A2: yes, the Tensorflow version is 1.12.0 with cuda9.0

Thanks, and I have runned it finally
Thanks, Best wishes to you!
