### ISSUE TITLE
pretrain model

### ISSUE THREAD

**Issue by Stonebobo** [kuihua/MSPFN#6]
Hi!,I want to know that where can I download **pre-trained models**?
I'm looking forward your reply as soon as pospible.

**Comment by kuihua** [comment]
ok, you can download the pre-trained model from the following link:
https://pan.baidu.com/s/1gq16HTvJCHEXXc0V3t7lqw 
提取码：zs3v

**Comment by Stonebobo** [comment]
thank you very much!Best wishes to you!

**Comment by Stonebobo** [comment]
I'm sorry, I'm here again. I get an error when I import your training model
**Key generator/URAB2_0/down2_1/alpha not found in checkpoint**
I would like to ask you to check whether the uploaded pre-trained model is correct
Thank you for your help!

**Comment by kuihua** [comment]
I am sorry for this problem. To facilitate your retraining and testing, the variable name have been changed in the file  (TEST_MSPFN.py). I have uploaded the raw test file (TEST_MSPFN_M17N1.py) . You can try it again.
