### ISSUE TITLE
downloading pretrain models

### ISSUE THREAD

**Issue by ejhung** [kuihua/MSPFN#8]
Hi kuihua, firstly thanks for sharing your work!

I was trying to download pretrained model and other stuff through Baidu's cloud but I wasn't able to succeed in both Linux and Mac. Is there any chance for you to upload the models and datasets in different platform such as google drive?

Thank you.

**Comment by kuihua** [comment]
Thanks for your attention! We have uploaded our pre-trained model to Google Drive, and you can download it from the following link:
https://drive.google.com/file/d/1nrjZtNs6AJYvfHi9TeCVTs50E57Fxgsc/view.
