### ISSUE TITLE
issues about premodel

### ISSUE THREAD

**Issue by ulen2000** [kuihua/MSPFN#9]
<img width="958" alt="360截图190008051009690" src="https://user-images.githubusercontent.com/58459187/87746619-98baa200-c823-11ea-8385-0e96c6ec45bc.png">
as you can see, the ./MSPFN/epoch50  is missing,and i can't find in your premodel

**Comment by kuihua** [comment]
You can change it  with epoch30, and then it will work.

**Comment by ulen2000** [comment]
yes,it works well~thanks
